### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by jkulubya** [jkulubya/liquibook.NET#1]
System.ArgumentException: An item with the same key has already been added. Key: [498, Liquibook.NET.Book.DepthLevel]
at System.Collections.Generic.TreeSet1.AddIfNotPresent(T item) at System.Collections.Generic.SortedDictionary2.Add(TKey key, TValue value)
at Liquibook.NET.Book.Depth.InsertLevelBefore(DepthLevel level, Boolean isBid, Price price)
at Liquibook.NET.Book.Depth.FindLevel(Price price, Boolean isBid, Boolean shouldCreate)
at Liquibook.NET.Book.Depth.AddOrder(Price price, Quantity quantity, Boolean isBid)
at Liquibook.NET.Book.DepthOrderBook.OnAccept(IOrder order, Quantity quantity)
at Liquibook.NET.Book.OrderBook.PerformCallback(Callback callback)
at Liquibook.NET.Book.OrderBook.CallbackNow()
at Liquibook.NET.Book.OrderBook.Add(IOrder order, OrderConditions orderConditions)

**Comment by jkulubya** [comment]
Actually fixed in https://github.com/jkulubya/liquibook.NET/commit/c35b51b0961cce6a5a981b4b1eaa87b43e4fa1d1
